version: "3.7"

services:
  php:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: dockerfiles/php.dockerfile
    image: keren-php
    container_name: keren-php
    user: 'sammy'
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - keren
    depends_on:
      - redis
      - mysql

  queue:
    image: keren-php
    container_name: keren-queue
    restart: always
    working_dir: /var/www/
    command: php artisan queue:work
    depends_on:
      - php
    volumes:
      - ./:/var/www
    networks:
      - keren

  redis:
    container_name: keren-redis
    image: redis:7.0
    volumes:
      - redis:/data
    networks:
      - keren

  mysql:
    image: mariadb:latest
    container_name: keren-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    volumes:
      - ./dockerfiles/mysql:/var/lib/mysql
    networks:
      - keren

  nginx:
    image: nginx:latest
    container_name: keren-nginx
    restart: unless-stopped
    ports:
      - "8800:80"
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - keren
    depends_on:
      - php

volumes:
  redis:
    name: keren-redis
    driver: "local"

networks:
  keren:
    driver: bridge
