version: '3.8'

networks:
    keren:
        name: keren-network
        driver: bridge

services:
    nginx:
        image: nginx:latest
        container_name: keren-nginx
        restart: unless-stopped
        ports:
            - "8800:80"
        volumes:
            - ./src:/var/www/html
            - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            - redis
            - mysql
        networks:
            - keren

    mysql:
        image: mariadb:10.11.2
        container_name: keren-mysql
        volumes:
            - ./mysql:/var/lib/mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: keren
            MYSQL_USER: sammy
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - keren

    redis:
        image: redis:7.0-alpine
        container_name: keren-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - keren

    php:
        image: keren/php
        build:
          context: ./dockerfiles
          dockerfile: php.dockerfile
          args:
              user: sammy
              uid: 1000
        container_name: keren-php
        restart: unless-stopped
        volumes:
          - ./src:/var/www/html
        networks:
          - keren

    composer:
        image: keren/composer
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: keren-composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        user: laravel
        entrypoint: [ 'composer', '--ignore-platform-reqs' ]
        networks:
            - keren

    artisan:
        image: keren/artisan
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                user: sammy
                uid: 1000
        container_name: keren-artisan
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
        working_dir: /var/www/html
        entrypoint: [ 'php', '/var/www/html/artisan' ]
        networks:
            - keren